name: nasa_clean_arch
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.4
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_modular: ^4.5.0
  flutter_triple: ^1.2.7+2
  http: ^0.13.4
  shimmer: ^2.0.0
  url_launcher: ^6.0.20
  youtube_player_iframe: ^2.2.2

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:

  uses-material-design: true